kind: Secret
apiVersion: v1
metadata:
  name: "{{ include "helm.fullname" .}}-secret"
stringData:
  EXAMPLE_ENV_VAR: "put your secrets env vars here"
  # in this case the value should be assigned inside cicd pipeline
  # best practise would be that it is summoned from hashicorp vault/conjur etc.
  ANOTHER_EXAMPLE: "{{ .Values.app.examplePassword }}"