stages:
- lint
- build
- deploy

variables:
  NAMESPACE: jojo
  APPNAME: kkt

build_image:
  stage: build
  # https://www.youtube.com/watch?v=qP8kir2GUgo&ab_channel=TechWorldwithNana
  image: docker:20.10.16
  services:
  - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  script:
  # ADD YOUR DOCKER USERNAME AND DOCKER PASS INTO GITLAB VARIABLES
  # !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker build -t $DOCKER_USER/$APPNAME .
  - docker push $DOCKER_USER/$APPNAME:latest

deploy:
  stage: deploy
  image: xgolis/deployimage:latest
  script:
  - sudo scp -i ./.ssh/id_rsa xgolis@34.163.90.124:/home/xgolis/.kube/config ~/.kube/config
  - sudo kubectl config set-cluster kubernetes --server=https://34.163.90.124:6443
  - sudo kubectl config set-cluster kubernetes --insecure-skip-tls-verify
  - kubectl get pods --namespace=$NAMESPACE
  # Add values to to helm upgrade if needed
  - helm upgrade $APPNAME 
    ./helm/$APPNAME 
    --install 
    -n $NAMESPACE
    --set "image.fullImage=$DOCKER_USER/$APPNAME:latest"
    --set "app.namespace=$NAMESPACE" 
    --set "app.examplePassword='pass'"
  # --set-file "app.exampleConfig="/path/to/config""
