stages:
- lint
- build
- deploy

variables:
  IMAGE_NAME: gog:1.8
  NAMESPACE: jojo
  APPNAME: kkt

# build_image:
#   stage: build
# # https://www.youtube.com/watch?v=qP8kir2GUgo&ab_channel=TechWorldwithNana
#   image: docker:20.10.16
#   services:
#     - docker:20.10.16-dind
#   variables:
#     DOCKER_TLS_CERTDIR: "/certs"
#   script:
#     - docker login -u $DOCKER_USER -p $DOCKER_PASS
#     - docker build -t $DOCKER_USER/$IMAGE_NAME .
#     - docker push $DOCKER_USER/$IMAGE_NAME

deploy:
  stage: deploy
  image: dtzar/helm-kubectl:3.11.2
  script: kubectl -u url -p -n helm upgrade
