apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helmcicdgenerator.fullname" . }}
  labels:
    {{- include "helmcicdgenerator.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ include "helmcicdgenerator.fullname" . }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ include "helmcicdgenerator.fullname" . }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "helmcicdgenerator.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.fullImage }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          envFrom:
            - secretRef:
                name: "{{ include "helmcicdgenerator.fullname" . }}-secret"
