apiVersion: apps/v1
kind: Service
metadata:
  labels:
    app: {{ include "helmcicdgenerator.fullname" . }}
  name: {{ include "helmcicdgenerator.fullname" . }}
  namespace: {{ .Values.app.namespace }}
spec:
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: {{ .Values.app.nodePort }}
    port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.port }}
  selector:
    app: {{ include "helmcicdgenerator.fullname" . }}
  sessionAffinity: None
  type: LoadBalancer